
exports.deleteticket = async (req, res) => {
  try {
    const ticketID = req.params.id;

    await Ticket.findByIdAndDelete(ticketID);
    
      await Reply.deleteMany({ ticketId: ticketID });
    res.json({ message: "Ticket deleted successfully!" });
  } catch (error) {
    console.log(error);
    res
      .status(500)
      .json({ message: "Internal Server Error", error: error.message });
  }
};